# -*- coding: utf-8 -*-
"""Capstone project - social media engagement analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfQVWnmzH4G5mLaoUhgXIuKGAWEoiFbt

**1. Data import and setup**
"""

import pandas as pd
import numpy as np
# import csv using pandas
df = pd.read_csv('social_media_engagement_5000.csv')
df

"""**B. Check data types**"""

df.dtypes

"""**C. Convert dates column to datetime**"""

df['posted_at'] = pd.to_datetime(df['posted_at'], errors='coerce')
df

"""**2. Imputation -- Data cleaning**
           a. cleaning missing values
"""

# Detecting missing value
df.isnull().sum()

# Filling numerical columns with average
df["age"]= df["age"].fillna(df["age"].mean())
df["likes"]= df["likes"].fillna(df["likes"].mean())
df["comments"]= df["comments"].fillna(df["comments"].mean())
df["shares"]= df["shares"].fillna(df["shares"].mean())
df.isnull().sum()

# count the values of gender and sentiment using value count
df["gender"].value_counts()

df["sentiment"].value_counts()

# Filling categorical column with own category
df["gender"] = df["gender"].fillna("unknown")
df["sentiment"] = df["sentiment"].fillna("unknown")
df.isnull().sum()

df

"""**b. Duplicates handling - identify and remove duplicates**"""

df.duplicated("user_id").sum()

df = df.drop_duplicates("user_id")

"""**C. Data Formatting**"""

# fix incorrect datatype
df.dtypes
df.info()

df = df.convert_dtypes()
df

# Standardise category
df["gender"] = df["gender"].str.lower().replace({'male': 'm', 'female' : 'f'})
df["device_type"] = df["device_type"].str.capitalize()
df["sentiment"] = df["sentiment"].str.capitalize()
df

# Correct unrealistic values
df = df[(df["likes"] >=0) & (df["comments"] >=0) & (df["shares"] >=0)]
df

"""**D. Feature Cleaning**"""

# Extract hashtags count
df['hashtag_count'] = df['hashtags'].apply(lambda x: len(str(x).split()))
df

# Clean setiment label
df["sentiment"] = df['sentiment'].str.lower().str.strip()
df

"""**3. Data Exploration**"""

# head -- It displays  5 rows and columns as default
df.head()

# Tail -- It displays bottom 5 rows and columns as default
df.tail()

# shape -- Give the shape of the data
df.shape

# columns -- Shows the name the columns in the data
df.columns

"""**b. Inspecting data types**"""

df.info()

df.dtypes

"""**c. Generate summary statistics**"""

df.describe()

"""**D. Analyse categorical distribution**

"""

df["post_type"].unique()

df["post_category"].nunique()

df["sentiment"].value_counts()

df["is_verified"].value_counts()

df["hashtags"].unique()

df["country"].unique()

df["device_type"].value_counts()

df["hashtags"].value_counts()

"""**E. Create correlation matrix for numeric field**"""

corr = df.corr(numeric_only=True)
corr

"""**F. Using groupby to summarize matrix**"""

avg_age = df.groupby('gender')['age'].mean()
avg_age

avg_comment = df.groupby('post_category')["comments"].mean()
avg_comment

avg_likes = df.groupby('post_type')["likes"].mean()
avg_likes

avg_impression = df.groupby('country')["impression_count"].mean()
avg_impression

"""**4. Data Wrangling**"""

# Creating a new features
df["engagement_score"] = df["likes"]+df["comments"]+df["shares"]
df

# performing groupby
avg_engagement_score = df.groupby(['post_type','sentiment'])['engagement_score'].mean()
avg_engagement_score

"""**5. Statistical Analysis**"""

# compute descriptive analysis
cols = ['likes', 'comments', 'shares', 'watch_time_sec', 'engagement_score', 'follower_count' ]

df[cols].mean()
df[cols].median()
df[cols].mode()
df[cols].std()
df[cols].var()
df[cols].quantile([0.25, 0.5, 0.75])

df

"""**6. Data Visualization**  **(i) Matplotlib**"""

import matplotlib.pyplot as plt

# line plot -- Daily engagement trends
df.groupby("posted_at")["engagement_score"].mean().plot(color = 'purple', linewidth = 2)
plt.title("Daily Engagement Trends")
plt.show()

# Bar Chart -- post by category
df['post_type'].value_counts().plot(kind='bar', color = "orange",)
plt.title("Posts by Category")
plt.show()

# pie chart -- gender distribution
df['gender'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.show()

# Histogram -- age
plt.hist(df['age'], bins=20, color = "red")
plt.title("Age Distribution")
plt.show()

# Box plot -- engagement rate
plt.boxplot(df["engagement_score"])
plt.title("Engagement Rate")
plt.show()

"""**(ii) Seaborn**

"""

# count plot -- post type
import seaborn as sns
# Setting a clean background style
sns.set_style("whitegrid")

plt.figure(figsize=(10, 6))

# Creating the count plot
# 'palette' options: 'viridis', 'plasma', 'flare', 'crest', 'magma'

ax = sns.countplot(data=df, x='post_type', hue = 'post_type', palette='flare', legend = False)

# Adding labels and title
plt.title('Total Distribution of Post Types', fontsize=15, fontweight='bold')
plt.xlabel('Post Type', fontsize=12)
plt.ylabel('Total Number of Posts', fontsize=12)
# Keep the annotations (optional but recommended)
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9),
                textcoords = 'offset points')

plt.show()

# pair plot -- numeric  features
# 1.  select the numeric feature
numeric_col = ["likes", "shares", "comments", "follower_count", "engagement_score"]
sns.set_style("white")
sns.set_context("paper", font_scale=1.2)
pair_plot = sns.pairplot(
    df[numeric_col + ['post_type']],
    hue='post_type',
    palette='husl',
    diag_kind='kde',
    plot_kws={'alpha': 0.6, 's': 30})
# 3. Final touches
plt.subplots_adjust(top=0.95)
pair_plot.fig.suptitle('Pairwise Relationships of Engagement Metrics', fontsize=16, fontweight='bold')
plt.show()

# Violin plot -- followers vs sentiments
sns.set_style("dark")
sns.violinplot(data=df, x= "sentiment", y="follower_count", hue = "sentiment", palette ="muted", split = True, inner = "quartile", legend = False)
plt.xlabel("Sentiment")
plt.ylabel("Followers count")
plt.title("Followers count by sentiment")
plt.show()

# 1. Calculate the correlation FIRST
# Use .corr() to turn your data into a correlation matrix
cor_matrix = df[["likes", "shares", "comments", "follower_count", "engagement_score"]].corr()

plt.figure(figsize=(10,6))

# 2. Fix the spelling of 'coolwarm'
sns.heatmap(cor_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)

plt.title("Correlation Matrix of Numerical Columns")
plt.show()

# Swarm plot -- engagement Vs device
plt.figure(figsize =(10,5))

sns.set_style("white")
sns.swarmplot(data=df.sample(2000), x = "device_type", y ="engagement_score", hue ="device_type", palette = "Set2", size =5, legend = True)
plt.title('Engagement Score Distribution by Device Type', fontsize=15, fontweight='bold')
plt.xlabel('Device Type', fontsize=12)
plt.ylabel('Engagement Score', fontsize=12)

plt.show()

import plotly.express as px

# Grouping data by date
daily_data = df.groupby('posted_at')['engagement_score'].mean().reset_index()

fig_line = px.line(daily_data, x='posted_at', y='engagement_score',
                  title='Interactive Daily Engagement Trend',
                  labels={'engagement_score': 'Avg Engagement', 'post_date': 'Date'},
                  template='plotly_white')

fig_line.show()